ebay/urls.py
from django.urls import path

from . import views

app_name = 'ebay'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
]

mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ebay.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ebay/models.py
from django.db import models

# Create your models here.

ebay/views.py
from django.http import HttpResponse
from django.shortcuts import render
import ebay.scraper as scraper
from django.template import loader

def index(request):
    return render(request, 'ebay/index.html')

def search(request):
    if request.method == 'POST':
        search = request.POST['search']
        data = scraper.get_data(search)
        return render(request, 'ebay/index.html', {'data': data})

ebay/templates/ebay/index.html
<html>
{% load static %}

<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous">
</script>
<link rel="stylesheet" href="{% static 'ebay/css/bootstrap.min.css' %}" >  
<script src="{% static 'ebay/js/bootstrap.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'ebay/style.css' %}">

<!-- Page title: Ebay tracker -->
<h1 class="text-center">Ebay Tracker</h1>
<!--  Search -->
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <form action="{% url 'ebay:search' %}" method="post">
        {% csrf_token %}
        <div class="input-group">
          <input type="text" class="form-control" name="search" placeholder="Search for...">
          <span class="input-group-btn">
            <button class="btn btn-default" type="submit">Go!</button>
          </span>
        </div><!-- /input-group -->
      </form>
    </div><!-- /.col-lg-6 -->
  </div><!-- /.row -->

<!-- some space -->
<br>

<!-- Display search results -->

{% if data %}
<div class="table-responsive-sm">
    <table class="table table-bordered table-hover">
        <thead class="thead-dark">
            <tr>
                <th scope='col'>#</th>
                <th scope='col'>Item Name</th>
                <th scope='col'>Condition</th>
                <th scope='col'>Price</th>
                <th scope='col'>Time left</th>
                <th scope='col'>Shipping cost</th>
            </tr>
        </thead>
    {% for item in data %}
        <tbody>
            <tr>
                <th scope="row">{{ forloop.counter0 }}</th>
                <td><a href="{{ item.itemlink }}"> {{ item.title }}</a></td>
                <td>{{ item.condition }}</td>
                <td>{{ item.price }}</td>
                <td>{{ item.timeleft }}</td>
                <td>{{ item.shippingcost }}</td>
            </tr>
        </tbody>
    {% endfor %}
    </table>
</div>
{% else %}
    <p>No item are available.</p>
{% endif %}

</html>